export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID'
export const ORDER = 'ORDER'

export const POST_ACTIVITY = 'POST_ACTIVITY'
